"""initial_schema_complete

Revision ID: b6fda1b76fbd
Revises: 
Create Date: 2026-03-21 00:49:26.635186

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b6fda1b76fbd'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_per_acre', sa.Float(), nullable=True),
    sa.Column('log_price_per_acre', sa.Float(), nullable=True),
    sa.Column('price_ksh', sa.Float(), nullable=True),
    sa.Column('size_acres', sa.Float(), nullable=True),
    sa.Column('amenities_score', sa.Float(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('infrastructure_score', sa.Float(), nullable=True),
    sa.Column('log_size_acres', sa.Float(), nullable=True),
    sa.Column('dist_to_nairobi_km', sa.Float(), nullable=True),
    sa.Column('geocode_confidence', sa.Float(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('dist_to_county_town_km', sa.Float(), nullable=True),
    sa.Column('dist_to_water_body_km', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_id'), 'parcels', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('prediction_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('size_acres', sa.Float(), nullable=False),
    sa.Column('zoning_type', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('predicted_price_ksh', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=True),
    sa.Column('full_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_id'), 'prediction_logs', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_logs_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parcels_id'), table_name='parcels')
    op.drop_index('idx_parcels_geom', table_name='parcels', postgresql_using='gist')
    op.drop_table('parcels')
    # ### end Alembic commands ###
